const { Router } = require('express')
const tag = require('./tag.js')
const categoria = require('./categoria.js')
const libro = require('./libro.js')
const review = require('./review.js')
const comentario = require('./comentario.js')
const pedido = require('./pedido')
const usuario = require('./usuario')
const formato = require('./formato')
const favorito = require('./favorito')
const auth = require('./auth')
const checkout = require('./checkout')

const router = Router()

router.use('/auth', auth)
router.use('/categorias', categoria)
router.use('/libros', libro)
router.use('/tags', tag)
router.use('/pedidos', pedido)
router.use('/usuarios', usuario)
router.use('/formatos', formato)
router.use('/favoritos', favorito)
router.use('/checkout', checkout)
router.use('/reviews', review)
router.use('/comentarios', comentario)

module.exports = router
